#!/bin/bash
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 43):
#
# Github Co-pilot & <jens@bennerhq.com> wrote this file.  As long as you 
# retain this notice you can do whatever you want with this stuff. If we meet 
# some day, and you think this stuff is worth it, you can buy me a beer in 
# return.   
#
# /benner
# ----------------------------------------------------------------------------

# This script reads the content of a YAML file and writes it to a C++ header
script_name=$(basename "$0")
if [ $# -lt 2 ]; then
    echo "Usage: $script_name <input_file> <output_file>"
    exit 1
fi

input_file="$1"
output_file="$2"

# Check if the input file is newer than the output file
if [ "$input_file" -nt "$output_file" ]; 
then
    # Read the content of the input file
    content=$(<"$input_file")

    # Write the content to the output file in the specified format
    echo '/*' > "$output_file"
    echo " * This file is auto generated." >> "$output_file"
    echo " * Don't edit, changes will be lost." >> "$output_file"
    echo " *" >> "$output_file"
    echo " * Edit $input_file to change the content of this file." >> "$output_file"
    echo " *" >> "$output_file"
    echo " * By running ./$script_name the content of this file is generate." >> "$output_file"
    echo ' */' >> "$output_file"
    echo '' >> "$output_file"
    echo 'R"(' >> "$output_file"
    echo "$content" >> "$output_file"
    echo ')"' >> "$output_file"

    # Set the output file's timestamp to match the input file's timestamp
    touch -r "$input_file" "$output_file"

    echo "$input_file: content written to $output_file."
fi
