#!/bin/bash
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 43):
#
# Github Co-pilot & <jens@bennerhq.com> wrote this file.  As long as you 
# retain this notice you can do whatever you want with this stuff. If we meet 
# some day, and you think this stuff is worth it, you can buy me a beer in 
# return.   
#
# /benner
# ----------------------------------------------------------------------------

# This script reads the content of a YAML file and writes it to a C++ header

input_file="./cclock.yaml"
output_file="./h/ConfigDefault.h"
include_file="./cpp/ConfigYAML.cpp"
script_name=$(basename "$0")

# Check if the input file is newer than the output file
if [ "$input_file" -nt "$output_file" ]; 
then
    # Read the content of the input file
    content=$(<"$input_file")

    # Write the content to the output file in the specified format
    echo '/*' > "$output_file"
    echo " * This file is auto generated." >> "$output_file"
    echo " * Don't edit, changes will be lost." >> "$output_file"
    echo " *" >> "$output_file"
    echo " * Edit $input_file to change the content of this file." >> "$output_file"
    echo " *" >> "$output_file"
    echo " * By running ./$script_name the content of this file is generate." >> "$output_file"
    echo " *" >> "$output_file"
    echo " * This file is included in $include_file" >> "$output_file"
    echo ' */' >> "$output_file"
    echo '' >> "$output_file"
    echo 'R"(' >> "$output_file"
    echo "$content" >> "$output_file"
    echo ')"' >> "$output_file"

    # Set the output file's timestamp to match the input file's timestamp
    touch -r "$input_file" "$output_file"

    echo "Content from $input_file has been written to $output_file in the specified format."
fi
